// Mock data for Slovak districts (okresy) - CL000024_OKRES
// DataTables format matching PAMIS API response

const okresyData = [
  ["221", "Bánovce nad Bebravou", "", ""],
  ["321", "Banská Bystrica", "", ""],
  ["322", "Banská Štiavnica", "", ""],
  ["411", "Bardejov", "", ""],
  ["101", "Bratislava I", "", ""],
  ["102", "Bratislava II", "", ""],
  ["103", "Bratislava III", "", ""],
  ["104", "Bratislava IV", "", ""],
  ["105", "Bratislava V", "", ""],
  ["323", "Brezno", "", ""],
  ["311", "Bytča", "", ""],
  ["312", "Čadca", "", ""],
  ["324", "Detva", "", ""],
  ["313", "Dolný Kubín", "", ""],
  ["211", "Dunajská Streda", "", ""],
  ["212", "Galanta", "", ""],
  ["421", "Gelnica", "", ""],
  ["213", "Hlohovec", "", ""],
  ["412", "Humenné", "", ""],
  ["222", "Ilava", "", ""],
  ["413", "Kežmarok", "", ""],
  ["231", "Komárno", "", ""],
  ["422", "Košice I", "", ""],
  ["423", "Košice II", "", ""],
  ["424", "Košice III", "", ""],
  ["425", "Košice IV", "", ""],
  ["426", "Košice - okolie", "", ""],
  ["325", "Krupina", "", ""],
  ["314", "Kysucké Nové Mesto", "", ""],
  ["232", "Levice", "", ""],
  ["414", "Levoča", "", ""],
  ["315", "Liptovský Mikuláš", "", ""],
  ["326", "Lučenec", "", ""],
  ["106", "Malacky", "", ""],
  ["316", "Martin", "", ""],
  ["415", "Medzilaborce", "", ""],
  ["427", "Michalovce", "", ""],
  ["223", "Myjava", "", ""],
  ["317", "Námestovo", "", ""],
  ["233", "Nitra", "", ""],
  ["224", "Nové Mesto nad Váhom", "", ""],
  ["234", "Nové Zámky", "", ""],
  ["225", "Partizánske", "", ""],
  ["107", "Pezinok", "", ""],
  ["214", "Piešťany", "", ""],
  ["327", "Poltár", "", ""],
  ["416", "Poprad", "", ""],
  ["226", "Považská Bystrica", "", ""],
  ["417", "Prešov", "", ""],
  ["227", "Prievidza", "", ""],
  ["228", "Púchov", "", ""],
  ["328", "Revúca", "", ""],
  ["329", "Rimavská Sobota", "", ""],
  ["428", "Rožňava", "", ""],
  ["318", "Ružomberok", "", ""],
  ["418", "Sabinov", "", ""],
  ["108", "Senec", "", ""],
  ["215", "Senica", "", ""],
  ["216", "Skalica", "", ""],
  ["419", "Snina", "", ""],
  ["429", "Sobrance", "", ""],
  ["42A", "Spišská Nová Ves", "", ""],
  ["41A", "Stará Ľubovňa", "", ""],
  ["41B", "Stropkov", "", ""],
  ["41C", "Svidník", "", ""],
  ["235", "Topoľčany", "", ""],
  ["42B", "Trebišov", "", ""],
  ["201", "Trnava", "", ""],
  ["229", "Trenčín", "", ""],
  ["319", "Turčianske Teplice", "", ""],
  ["31A", "Tvrdošín", "", ""],
  ["32A", "Veľký Krtíš", "", ""],
  ["41D", "Vranov nad Topľou", "", ""],
  ["236", "Zlaté Moravce", "", ""],
  ["32B", "Zvolen", "", ""],
  ["32C", "Žarnovica", "", ""],
  ["32D", "Žiar nad Hronom", "", ""],
  ["31B", "Žilina", "", ""]
];

module.exports = okresyData;
