// Mock data for Slovak districts (okresy) - CL000024_OKRES
// Based on standard Slovak administrative division

const okresyData = [
  { kod: "BA1", nazov: "Bratislava I", kraj: "Bratislavský" },
  { kod: "BA2", nazov: "Bratislava II", kraj: "Bratislavský" },
  { kod: "BA3", nazov: "Bratislava III", kraj: "Bratislavský" },
  { kod: "BA4", nazov: "Bratislava IV", kraj: "Bratislavský" },
  { kod: "BA5", nazov: "Bratislava V", kraj: "Bratislavský" },
  { kod: "MA", nazov: "Malacky", kraj: "Bratislavský" },
  { kod: "PK", nazov: "Pezinok", kraj: "Bratislavský" },
  { kod: "SC", nazov: "Senec", kraj: "Bratislavský" },
  { kod: "DS", nazov: "Dunajská Streda", kraj: "Trnavský" },
  { kod: "GA", nazov: "Galanta", kraj: "Trnavský" },
  { kod: "HC", nazov: "Hlohovec", kraj: "Trnavský" },
  { kod: "PD", nazov: "Piešťany", kraj: "Trnavský" },
  { kod: "SL", nazov: "Senica", kraj: "Trnavský" },
  { kod: "SI", nazov: "Skalica", kraj: "Trnavský" },
  { kod: "TT", nazov: "Trnava", kraj: "Trnavský" },
  { kod: "BN", nazov: "Bánovce nad Bebravou", kraj: "Trenčiansky" },
  { kod: "IL", nazov: "Ilava", kraj: "Trenčiansky" },
  { kod: "MY", nazov: "Myjava", kraj: "Trenčiansky" },
  { kod: "NM", nazov: "Nové Mesto nad Váhom", kraj: "Trenčiansky" },
  { kod: "PB", nazov: "Považská Bystrica", kraj: "Trenčiansky" },
  { kod: "PD", nazov: "Prievidza", kraj: "Trenčiansky" },
  { kod: "PU", nazov: "Púchov", kraj: "Trenčiansky" },
  { kod: "TN", nazov: "Trenčín", kraj: "Trenčiansky" },
  { kod: "BA", nazov: "Bytča", kraj: "Žilinský" },
  { kod: "CA", nazov: "Čadca", kraj: "Žilinský" },
  { kod: "DK", nazov: "Dolný Kubín", kraj: "Žilinský" },
  { kod: "KM", nazov: "Kysucké Nové Mesto", kraj: "Žilinský" },
  { kod: "LM", nazov: "Liptovský Mikuláš", kraj: "Žilinský" },
  { kod: "MT", nazov: "Martin", kraj: "Žilinský" },
  { kod: "NO", nazov: "Námestovo", kraj: "Žilinský" },
  { kod: "RK", nazov: "Ružomberok", kraj: "Žilinský" },
  { kod: "TR", nazov: "Turčianske Teplice", kraj: "Žilinský" },
  { kod: "TV", nazov: "Tvrdošín", kraj: "Žilinský" },
  { kod: "ZA", nazov: "Žilina", kraj: "Žilinský" },
  { kod: "BB", nazov: "Banská Bystrica", kraj: "Banskobystrický" },
  { kod: "BS", nazov: "Banská Štiavnica", kraj: "Banskobystrický" },
  { kod: "BR", nazov: "Brezno", kraj: "Banskobystrický" },
  { kod: "DT", nazov: "Detva", kraj: "Banskobystrický" },
  { kod: "KA", nazov: "Krupina", kraj: "Banskobystrický" },
  { kod: "LC", nazov: "Lučenec", kraj: "Banskobystrický" },
  { kod: "PE", nazov: "Poltár", kraj: "Banskobystrický" },
  { kod: "RA", nazov: "Revúca", kraj: "Banskobystrický" },
  { kod: "RS", nazov: "Rimavská Sobota", kraj: "Banskobystrický" },
  { kod: "VK", nazov: "Veľký Krtíš", kraj: "Banskobystrický" },
  { kod: "ZC", nazov: "Zvolen", kraj: "Banskobystrický" },
  { kod: "ZH", nazov: "Žarnovica", kraj: "Banskobystrický" },
  { kod: "ZI", nazov: "Žiar nad Hronom", kraj: "Banskobystrický" },
  { kod: "BJ", nazov: "Bardejov", kraj: "Prešovský" },
  { kod: "HE", nazov: "Humenné", kraj: "Prešovský" },
  { kod: "KK", nazov: "Kežmarok", kraj: "Prešovský" },
  { kod: "LE", nazov: "Levoča", kraj: "Prešovský" },
  { kod: "ML", nazov: "Medzilaborce", kraj: "Prešovský" },
  { kod: "PP", nazov: "Poprad", kraj: "Prešovský" },
  { kod: "PO", nazov: "Prešov", kraj: "Prešovský" },
  { kod: "SB", nazov: "Sabinov", kraj: "Prešovský" },
  { kod: "SN", nazov: "Snina", kraj: "Prešovský" },
  { kod: "SP", nazov: "Stará Ľubovňa", kraj: "Prešovský" },
  { kod: "SK", nazov: "Stropkov", kraj: "Prešovský" },
  { kod: "SV", nazov: "Svidník", kraj: "Prešovský" },
  { kod: "VT", nazov: "Vranov nad Topľou", kraj: "Prešovský" },
  { kod: "GL", nazov: "Gelnica", kraj: "Košický" },
  { kod: "KS", nazov: "Košice I", kraj: "Košický" },
  { kod: "KE", nazov: "Košice II", kraj: "Košický" },
  { kod: "K3", nazov: "Košice III", kraj: "Košický" },
  { kod: "K4", nazov: "Košice IV", kraj: "Košický" },
  { kod: "KO", nazov: "Košice-okolie", kraj: "Košický" },
  { kod: "MI", nazov: "Michalovce", kraj: "Košický" },
  { kod: "RV", nazov: "Rožňava", kraj: "Košický" },
  { kod: "SO", nazov: "Sobrance", kraj: "Košický" },
  { kod: "TS", nazov: "Trebišov", kraj: "Košický" },
  { kod: "KN", nazov: "Komárno", kraj: "Nitriansky" },
  { kod: "LV", nazov: "Levice", kraj: "Nitriansky" },
  { kod: "NR", nazov: "Nitra", kraj: "Nitriansky" },
  { kod: "NI", nazov: "Nové Zámky", kraj: "Nitriansky" },
  { kod: "SA", nazov: "Šaľa", kraj: "Nitriansky" },
  { kod: "TO", nazov: "Topoľčany", kraj: "Nitriansky" },
  { kod: "ZM", nazov: "Zlaté Moravce", kraj: "Nitriansky" }
];

module.exports = okresyData;
